language: node_js
node_js:
- 9.3.0
after_success:
- ssh root@104.153.97.131 -p 28733 'cd /home/www/oChat-client && git pull'
before_install:
- openssl aes-256-cbc -K $encrypted_daa7f929f1cc_key -iv $encrypted_daa7f929f1cc_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 104.153.97.131\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
